"""Initial Migration

Revision ID: 1abb9b6805a5
Revises: 4965ed66d657
Create Date: 2021-09-27 18:03:38.832747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abb9b6805a5'
down_revision = '4965ed66d657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blog_user_id_fkey', 'blog', type_='foreignkey')
    op.drop_column('blog', 'user_id')
    op.drop_constraint('votes_blog_id_fkey', 'votes', type_='foreignkey')
    op.drop_column('votes', 'blog_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('votes_blog_id_fkey', 'votes', 'blog', ['blog_id'], ['id'])
    op.add_column('blog', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('blog_user_id_fkey', 'blog', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
