"""Initial Migration

Revision ID: ae0fa66ae897
Revises: 1b5c9ed31ca7
Create Date: 2021-09-28 10:30:13.241126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0fa66ae897'
down_revision = '1b5c9ed31ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('author', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'author')
    # ### end Alembic commands ###
